--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_EMAIL_CONTENT
--------------------------------------------------------

  CREATE TABLE "CSM_EMAIL_CONTENT" 
   (	"EMCNT_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"EMCNT_NOTIFICATION_TYPE" VARCHAR2(100 BYTE), 
	"EMCNT_SUBJECT" VARCHAR2(100 BYTE), 
	"EMCNT_BODY" VARCHAR2(100 BYTE), 
	"EMCNT_IS_ATTACHREPORT" NUMBER(1,0), 
	"EMCNT_SIGNATURE" VARCHAR2(100 BYTE), 
	"EMCNT_REPLYTO" VARCHAR2(100 BYTE), 
	"EMCNT_IS_ACTIVE" NUMBER(1,0), 
	"EMCNT_CREATED_BY" TIMESTAMP (3), 
	"EMCNT_CREATED_DATE" VARCHAR2(100 BYTE), 
	"EMCNT_UPDATED_BY" TIMESTAMP (3), 
	"EMCNT_UPDATED_DATE" VARCHAR2(2000 BYTE), 
	"EMCNT_COMMENTS" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_EMAIL_CONTENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_EMAIL_CONTENT" ON "CSM_EMAIL_CONTENT" ("EMCNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_EMAIL_CONTENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_EMAIL_CONTENT_SEQ_TR" 
 BEFORE INSERT ON CSM_EMAIL_CONTENT FOR EACH ROW
  WHEN (NEW.EMCNT_ID IS NULL) BEGIN
 SELECT CSM_EMAIL_CONTENT_seq.NEXTVAL INTO :NEW.EMCNT_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_EMAIL_CONTENT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_EMAIL_CONTENT
--------------------------------------------------------

  ALTER TABLE "CSM_EMAIL_CONTENT" ADD CONSTRAINT "PK_CSM_EMAIL_CONTENT" PRIMARY KEY ("EMCNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_EMAIL_CONTENT" MODIFY ("EMCNT_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_CONTENT" MODIFY ("EMCNT_NOTIFICATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_CONTENT" MODIFY ("EMCNT_ID" NOT NULL ENABLE);

exit;