--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_GROUP_DETAIL
--------------------------------------------------------

  CREATE TABLE "CSM_GROUP_DETAIL" 
   (	"GROUP_DETAIL_ID" NUMBER(10,0), 
	"GROUP_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"WIN_SERVICE_ID" NUMBER(10,0), 
	"GROUP_CREATED_BY" VARCHAR2(100 BYTE), 
	"GROUP_CREATED_DATE" TIMESTAMP (3), 
	"GROUP_UPDATED_BY" VARCHAR2(100 BYTE), 
	"GROUP_UPDATED_DATE" TIMESTAMP (3), 
	"GROUP_DETAIL_COMMENTS" VARCHAR2(2000 BYTE), 
	"GROUP_ISACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_GROUP_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_GROUP_DETAIL" ON "CSM_GROUP_DETAIL" ("GROUP_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_GROUP_DETAIL_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_GROUP_DETAIL_SEQ_TR" 
 BEFORE INSERT ON CSM_GROUP_DETAIL FOR EACH ROW
  WHEN (NEW.GROUP_DETAIL_ID IS NULL) BEGIN
 SELECT CSM_GROUP_DETAIL_seq.NEXTVAL INTO :NEW.GROUP_DETAIL_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_GROUP_DETAIL_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_GROUP_DETAIL
--------------------------------------------------------

  ALTER TABLE "CSM_GROUP_DETAIL" ADD CONSTRAINT "PK_CSM_GROUP_DETAIL" PRIMARY KEY ("GROUP_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_GROUP_DETAIL" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_GROUP_DETAIL" MODIFY ("ENV_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_GROUP_DETAIL" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_GROUP_DETAIL" MODIFY ("GROUP_DETAIL_ID" NOT NULL ENABLE);

exit;