--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_INCIDENT
--------------------------------------------------------

  CREATE TABLE "CSM_INCIDENT" 
   (	"TRK_ID" NUMBER(10,0), 
	"MON_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"TRK_ISSUE" VARCHAR2(4000 BYTE), 
	"TRK_SOLUTION" VARCHAR2(4000 BYTE), 
	"TRK_CREATED_BY" VARCHAR2(100 BYTE), 
	"TRK_CREATED_DATE" TIMESTAMP (3), 
	"TRK_UPDATED_BY" VARCHAR2(100 BYTE), 
	"TRK_UPDATED_DATE" TIMESTAMP (3), 
	"TRK_COMMENTS" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_INCIDENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_INCIDENT" ON "CSM_INCIDENT" ("TRK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_INCIDENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_INCIDENT_SEQ_TR" 
 BEFORE INSERT ON CSM_INCIDENT FOR EACH ROW
  WHEN (NEW.TRK_ID IS NULL) BEGIN
 SELECT CSM_INCIDENT_seq.NEXTVAL INTO :NEW.TRK_ID FROM DUAL;
END;
/
ALTER TRIGGER "CSM_INCIDENT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_INCIDENT
--------------------------------------------------------

  ALTER TABLE "CSM_INCIDENT" ADD CONSTRAINT "PK_CSM_INCIDENT" PRIMARY KEY ("TRK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_INCIDENT" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_INCIDENT" MODIFY ("MON_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_INCIDENT" MODIFY ("TRK_ID" NOT NULL ENABLE);

exit;