--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_MENUS
--------------------------------------------------------

  CREATE TABLE "CSM_MENUS" 
   (	"MENU_ID" NUMBER(10,0), 
	"MENU_MAIN" VARCHAR2(100 BYTE), 
	"MENU_SUB" VARCHAR2(100 BYTE), 
	"MENU_PATH" VARCHAR2(100 BYTE), 
	"MENU_ISPOPUP" NUMBER(1,0), 
	"MENU_ISACTIVE" NUMBER(1,0), 
	"MENU_MAIN_ORDER" NUMBER(10,0), 
	"MENU_SUB_ORDER" NUMBER(10,0), 
	"MENU_COMMENTS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_MENUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_MENUS" ON "CSM_MENUS" ("MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_MENUS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_MENUS_SEQ_TR" 
 BEFORE INSERT ON CSM_MENUS FOR EACH ROW
  WHEN (NEW.MENU_ID IS NULL) BEGIN
 SELECT CSM_MENUS_seq.NEXTVAL INTO :NEW.MENU_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_MENUS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_MENUS
--------------------------------------------------------

  ALTER TABLE "CSM_MENUS" ADD CONSTRAINT "PK_CSM_MENUS" PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_MENUS" MODIFY ("MENU_PATH" NOT NULL ENABLE);
  ALTER TABLE "CSM_MENUS" MODIFY ("MENU_SUB" NOT NULL ENABLE);
  ALTER TABLE "CSM_MENUS" MODIFY ("MENU_MAIN" NOT NULL ENABLE);
  ALTER TABLE "CSM_MENUS" MODIFY ("MENU_ID" NOT NULL ENABLE);

exit;