--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_EMAIL_TRACKING
--------------------------------------------------------

  CREATE TABLE "CSM_EMAIL_TRACKING" 
   (	"EMTRAC_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"EMTRAC_TO_ADDRESS" VARCHAR2(200 BYTE), 
	"EMTRAC_CC_ADDRESS" VARCHAR2(200 BYTE), 
	"EMTRAC_BCC_ADDRESS" VARCHAR2(200 BYTE), 
	"EMTRAC_SUBJECT" VARCHAR2(500 BYTE), 
	"EMTRAC_BODY" VARCHAR2(4000 BYTE), 
	"EMTRAC_SEND_STATUS" VARCHAR2(500 BYTE), 
	"EMTRAC_SEND_ERROR" VARCHAR2(4000 BYTE), 
	"EMTRAC_CONTENT_TYPE" VARCHAR2(200 BYTE), 
	"EMTRAC_IS_ACTIVE" NUMBER(1,0), 
	"EMTRAC_CREATED_BY" VARCHAR2(100 BYTE), 
	"EMTRAC_CREATED_DATE" TIMESTAMP (3), 
	"EMTRAC_UPDATED_BY" VARCHAR2(100 BYTE), 
	"EMTRAC_UPDATED_DATE" TIMESTAMP (3), 
	"EMTRAC_COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_EMAIL_TRACKING
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_EMAIL_TRACKING" ON "CSM_EMAIL_TRACKING" ("EMTRAC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_EMAIL_TRACKING_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_EMAIL_TRACKING_SEQ_TR" 
 BEFORE INSERT ON CSM_EMAIL_TRACKING FOR EACH ROW
  WHEN (NEW.EMTRAC_ID IS NULL) BEGIN
 SELECT CSM_EMAIL_TRACKING_seq.NEXTVAL INTO :NEW.EMTRAC_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_EMAIL_TRACKING_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_EMAIL_TRACKING
--------------------------------------------------------

  ALTER TABLE "CSM_EMAIL_TRACKING" ADD CONSTRAINT "PK_CSM_EMAIL_TRACKING" PRIMARY KEY ("EMTRAC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_EMAIL_TRACKING" MODIFY ("EMTRAC_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_TRACKING" MODIFY ("EMTRAC_TO_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_TRACKING" MODIFY ("EMTRAC_ID" NOT NULL ENABLE);

exit;