--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "CSM_USER_ROLE" 
   (	"USER_ROLE_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"ROLE_ID" NUMBER(10,0), 
	"USER_ROLE_ISACTIVE" NUMBER(1,0), 
	"USER_CREATED_BY" VARCHAR2(100 BYTE), 
	"USER_CREATED_DATE" TIMESTAMP (3), 
	"USER_UPDATED_BY" VARCHAR2(100 BYTE), 
	"USER_UPDATED_DATE" TIMESTAMP (3), 
	"USER_COMMENTS" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_USER_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_USER_ROLE" ON "CSM_USER_ROLE" ("USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_USER_ROLE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_USER_ROLE_SEQ_TR" 
 BEFORE INSERT ON CSM_USER_ROLE FOR EACH ROW
  WHEN (NEW.USER_ROLE_ID IS NULL) BEGIN
 SELECT CSM_USER_ROLE_seq.NEXTVAL INTO :NEW.USER_ROLE_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_USER_ROLE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "CSM_USER_ROLE" ADD CONSTRAINT "PK_CSM_USER_ROLE" PRIMARY KEY ("USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_USER_ROLE" MODIFY ("USER_ROLE_ID" NOT NULL ENABLE);

exit;