--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_ROLES
--------------------------------------------------------

  CREATE TABLE "CSM_ROLES" 
   (	"ROLE_ID" NUMBER(10,0), 
	"ROLE_NAME" VARCHAR2(100 BYTE), 
	"ROLE_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ROLE_TYPE" VARCHAR2(100 BYTE), 
	"ROLE_ISACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_USER_ROLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_USER_ROLES" ON "CSM_ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_ROLES_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_ROLES_SEQ_TR" 
 BEFORE INSERT ON CSM_ROLES FOR EACH ROW
  WHEN (NEW.ROLE_ID IS NULL) BEGIN
 SELECT CSM_ROLES_seq.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_ROLES_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_ROLES
--------------------------------------------------------

  ALTER TABLE "CSM_ROLES" ADD CONSTRAINT "PK_CSM_USER_ROLES" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);

exit;