--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_LOG
--------------------------------------------------------

  CREATE TABLE "CSM_LOG" 
   (	"LOGID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"SCH_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"LOGDESCRIPTION" VARCHAR2(1000 BYTE), 
	"LOGERROR" VARCHAR2(1000 BYTE), 
	"LOG_UPDATED_DATETIME" TIMESTAMP (3), 
	"LOG_UPDATED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_LOG" ON "CSM_LOG" ("LOGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_LOG_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_LOG_SEQ_TR" 
 BEFORE INSERT ON CSM_LOG FOR EACH ROW
  WHEN (NEW.LOGID IS NULL) BEGIN
 SELECT CSM_LOG_seq.NEXTVAL INTO :NEW.LOGID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_LOG_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_LOG
--------------------------------------------------------

  ALTER TABLE "CSM_LOG" ADD CONSTRAINT "PK_CSM_LOG" PRIMARY KEY ("LOGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_LOG" MODIFY ("LOGID" NOT NULL ENABLE);

exit;