--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_WINDOWS_SERVICES
--------------------------------------------------------

  CREATE TABLE "CSM_WINDOWS_SERVICES" 
   (	"WIN_SERVICE_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"WIN_SERVICENAME" VARCHAR2(200 BYTE), 
	"WIN_COMMENTS" VARCHAR2(2000 BYTE), 
	"WIN_CREATED_BY" VARCHAR2(100 BYTE), 
	"WIN_CREATED_DATE" TIMESTAMP (3), 
	"WIN_UPDATED_BY" VARCHAR2(100 BYTE), 
	"WIN_UPDATED_DATE" TIMESTAMP (3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_WINDOWS_SERVICES_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_WINDOWS_SERVICES_SEQ_TR" 
 BEFORE INSERT ON CSM_WINDOWS_SERVICES FOR EACH ROW
  WHEN (NEW.WIN_SERVICE_ID IS NULL) BEGIN
 SELECT CSM_WINDOWS_SERVICES_seq.NEXTVAL INTO :NEW.WIN_SERVICE_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_WINDOWS_SERVICES_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_WINDOWS_SERVICES
--------------------------------------------------------

  ALTER TABLE "CSM_WINDOWS_SERVICES" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_WINDOWS_SERVICES" MODIFY ("ENV_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_WINDOWS_SERVICES" MODIFY ("WIN_SERVICE_ID" NOT NULL ENABLE);

exit;