--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_EMAIL_CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "CSM_EMAIL_CONFIGURATION" 
   (	"EMAIL_SERVER_ID" NUMBER(10,0), 
	"EMAIL_SERVER_NAME" VARCHAR2(100 BYTE), 
	"EMAIL_SERVER_IPADDRESS" VARCHAR2(100 BYTE), 
	"EMAIL_SERVER_PORT" VARCHAR2(100 BYTE), 
	"EMAIL_AUTH_USER_ID" VARCHAR2(100 BYTE), 
	"EMAIL_AUTH_USER_PWD" VARCHAR2(100 BYTE), 
	"EMAIL_DEFAULT_SENDER" VARCHAR2(100 BYTE), 
	"EMAIL_IS_ACTIVE" NUMBER(1,0), 
	"EMAIL_CREATED_BY" VARCHAR2(100 BYTE), 
	"EMAIL_CREATED_DATE" TIMESTAMP (3), 
	"EMAIL_UPDATED_BY" VARCHAR2(100 BYTE), 
	"EMAIL_UPDATED_DATE" TIMESTAMP (3), 
	"EMAIL_COMMENTS" VARCHAR2(2000 BYTE), 
	"EMAIL_SSL_ENABLE" NUMBER(1,0), 
	"EMAIL_ADMIN_MAILADRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_EMAIL_CONFIGURATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_EMAIL_CONFIGURATION" ON "CSM_EMAIL_CONFIGURATION" ("EMAIL_SERVER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_EMAIL_CONFIGURATION_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_EMAIL_CONFIGURATION_SEQ_TR" 
 BEFORE INSERT ON CSM_EMAIL_CONFIGURATION FOR EACH ROW
  WHEN (NEW.EMAIL_SERVER_ID IS NULL) BEGIN
 SELECT CSM_EMAIL_CONFIGURATION_seq.NEXTVAL INTO :NEW.EMAIL_SERVER_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_EMAIL_CONFIGURATION_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_EMAIL_CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "CSM_EMAIL_CONFIGURATION" ADD CONSTRAINT "PK_CSM_EMAIL_CONFIGURATION" PRIMARY KEY ("EMAIL_SERVER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_EMAIL_CONFIGURATION" MODIFY ("EMAIL_IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_CONFIGURATION" MODIFY ("EMAIL_AUTH_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_CONFIGURATION" MODIFY ("EMAIL_SERVER_PORT" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_CONFIGURATION" MODIFY ("EMAIL_SERVER_IPADDRESS" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_CONFIGURATION" MODIFY ("EMAIL_SERVER_NAME" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_CONFIGURATION" MODIFY ("EMAIL_SERVER_ID" NOT NULL ENABLE);

exit;