--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "CSM_CONFIGURATION" 
   (	"CONFIG_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONFIG_SERVICE_TYPE" VARCHAR2(30 BYTE), 
	"CONFIG_PORT_NUMBER" VARCHAR2(10 BYTE), 
	"CONFIG_URL_ADDRESS" VARCHAR2(500 BYTE), 
	"CONFIG_DESCRIPTION" VARCHAR2(500 BYTE), 
	"CONFIG_IS_VALIDATED" NUMBER(1,0), 
	"CONFIG_IS_ACTIVE" NUMBER(1,0), 
	"CONFIG_IS_MONITORED" NUMBER(1,0), 
	"CONFIG_IS_LOCKED" NUMBER(1,0), 
	"CONFIG_CREATED_BY" VARCHAR2(100 BYTE), 
	"CONFIG_CREATED_DATE" TIMESTAMP (3), 
	"CONFIG_UPDATED_BY" VARCHAR2(100 BYTE), 
	"CONFIG_UPDATED_DATE" TIMESTAMP (3), 
	"CONFIG_COMMENTS" VARCHAR2(2000 BYTE), 
	"CONFIG_HOST_IP" VARCHAR2(100 BYTE) DEFAULT ('10.12.110.111'), 
	"CONFIG_MAIL_FREQ" NUMBER(10,0), 
	"CONFIG_LOCATION" VARCHAR2(200 BYTE), 
	"CONFIG_ISCONSOLIDATED" NUMBER(1,0), 
	"CONFIG_ISNOTIFY" NUMBER(1,0), 
	"CONFIG_ISPRIMARY" NUMBER(1,0), 
	"CONFIG_REF_ID" NUMBER(10,0), 
	"CONFIG_ISNOTIFY_MAIN" NUMBER(1,0), 
	"CONFIG_COLUMN1" VARCHAR2(100 BYTE), 
	"CONFIG_COLUMN2" VARCHAR2(100 BYTE), 
	"CONFIG_COLUMN3" VARCHAR2(100 BYTE), 
	"CONFIG_COLUMN4" VARCHAR2(100 BYTE), 
	"CONFIG_COLUMN5" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_CONFIGURATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_CONFIGURATION" ON "CSM_CONFIGURATION" ("CONFIG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  --------------------------------------------------------
--  DDL for Trigger CSM_CONFIGURATION_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_CONFIGURATION_SEQ_TR" 
 BEFORE INSERT ON CSM_CONFIGURATION FOR EACH ROW
  WHEN (NEW.CONFIG_ID IS NULL) BEGIN
 SELECT CSM_CONFIGURATION_seq.NEXTVAL INTO :NEW.CONFIG_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_CONFIGURATION_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "CSM_CONFIGURATION" ADD CONSTRAINT "PK_CSM_CONFIGURATION" PRIMARY KEY ("CONFIG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_IS_LOCKED" NOT NULL ENABLE);
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_IS_MONITORED" NOT NULL ENABLE);
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_IS_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_IS_VALIDATED" NOT NULL ENABLE);
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_URL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_PORT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_SERVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CSM_CONFIGURATION" MODIFY ("CONFIG_ID" NOT NULL ENABLE);

  
  exit;