--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_GROUP_SCHEDULE_DETAIL
--------------------------------------------------------

  CREATE TABLE "CSM_GROUP_SCHEDULE_DETAIL" 
   (	"GROUP_SERVICE_SCH_ID" NUMBER(10,0), 
	"GROUP_SCH_ID" NUMBER(10,0), 
	"GROUP_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"GROUP_SCH_ISACTIVE" NUMBER(1,0), 
	"GROUP_SCH_STATUS" VARCHAR2(20), 
	"GROUP_SCH_UPDATEDTIME" TIMESTAMP (3) DEFAULT SYSTIMESTAMP, 
	"GROUP_SCH_RESULT" VARCHAR2(50 BYTE), 
	"GROUP_SCH_SERVICE_STARTTIME" TIMESTAMP (3), 
	"GROUP_SCH_SERVICE_COMPTIME" TIMESTAMP (3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_GROUP_SCHEDULE_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_GROUP_SCHEDULE_DETAIL" ON "CSM_GROUP_SCHEDULE_DETAIL" ("GROUP_SERVICE_SCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_GROUP_SCHEDULE_DL_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_GROUP_SCHEDULE_DL_SEQ_TR" 
 BEFORE INSERT ON CSM_GROUP_SCHEDULE_DETAIL FOR EACH ROW
  WHEN (NEW.GROUP_SERVICE_SCH_ID IS NULL) BEGIN
 SELECT CSM_GROUP_SCHEDULE_DETAIL_seq.NEXTVAL INTO :NEW.GROUP_SERVICE_SCH_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_GROUP_SCHEDULE_DL_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_GROUP_SCHEDULE_DETAIL
--------------------------------------------------------

  ALTER TABLE "CSM_GROUP_SCHEDULE_DETAIL" ADD CONSTRAINT "PK_CSM_GROUP_SCHEDULE_DETAIL" PRIMARY KEY ("GROUP_SERVICE_SCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_GROUP_SCHEDULE_DETAIL" MODIFY ("GROUP_SERVICE_SCH_ID" NOT NULL ENABLE);

exit;