--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_ENVIRONEMENT
--------------------------------------------------------

  CREATE TABLE "CSM_ENVIRONEMENT" 
   (	"ENV_ID" NUMBER(10,0), 
	"ENV_NAME" VARCHAR2(100 BYTE), 
	"ENV_IS_MONITOR" NUMBER(1,0), 
	"ENV_IS_NOTIFY" NUMBER(1,0) DEFAULT ((1)), 
	"ENV_CREATED_BY" VARCHAR2(100 BYTE), 
	"ENV_CREATED_DATE" TIMESTAMP (3), 
	"ENV_UPDATED_BY" VARCHAR2(100 BYTE), 
	"ENV_UPDATED_DATE" TIMESTAMP (3), 
	"ENV_COMMENTS" VARCHAR2(2000 BYTE), 
	"ENV_MAIL_FREQ" NUMBER(10,0), 
	"ENV_IS_CONSLTD_MAIL" NUMBER(1,0), 
	"ENV_ISACTIVE" NUMBER(1,0), 
	"ENV_SORTORDER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_ENVIRONEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_ENVIRONEMENT" ON "CSM_ENVIRONEMENT" ("ENV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_ENVIRONEMENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_ENVIRONEMENT_SEQ_TR" 
 BEFORE INSERT ON CSM_ENVIRONEMENT FOR EACH ROW
  WHEN (NEW.ENV_ID IS NULL) BEGIN
 SELECT CSM_ENVIRONEMENT_seq.NEXTVAL INTO :NEW.ENV_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_ENVIRONEMENT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_ENVIRONEMENT
--------------------------------------------------------

  ALTER TABLE "CSM_ENVIRONEMENT" ADD CONSTRAINT "PK_CSM_ENVIRONEMENT" PRIMARY KEY ("ENV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_ENVIRONEMENT" MODIFY ("ENV_NAME" NOT NULL ENABLE);
  ALTER TABLE "CSM_ENVIRONEMENT" MODIFY ("ENV_ID" NOT NULL ENABLE);

exit;  