--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_REPORT_SUBS_DETAILS
--------------------------------------------------------

  CREATE TABLE "CSM_REPORT_SUBS_DETAILS" 
   (	"SUBSCRIPTION_DETAIL_ID" NUMBER(10,0), 
	"SUBSCRIPTION_ID" NUMBER(10,0), 
	"USRLST_ID" NUMBER(10,0), 
	"SUBSCRIPTION_EMAILID" VARCHAR2(100 BYTE), 
	"SUBSCRIPTION_ISACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_REPORT_SUBS_DETAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_REPORT_SUBS_DETAILS" ON "CSM_REPORT_SUBS_DETAILS" ("SUBSCRIPTION_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_REPORT_SUBS_DETAILS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_REPORT_SUBS_DETAILS_SEQ_TR" 
 BEFORE INSERT ON CSM_REPORT_SUBS_DETAILS FOR EACH ROW
  WHEN (NEW.SUBSCRIPTION_DETAIL_ID IS NULL) BEGIN
 SELECT CSM_REPORT_SUBS_DETAILS_seq.NEXTVAL INTO :NEW.SUBSCRIPTION_DETAIL_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_REPORT_SUBS_DETAILS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_REPORT_SUBS_DETAILS
--------------------------------------------------------

  ALTER TABLE "CSM_REPORT_SUBS_DETAILS" ADD CONSTRAINT "PK_CSM_REPORT_SUBS_DETAILS" PRIMARY KEY ("SUBSCRIPTION_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_REPORT_SUBS_DETAILS" MODIFY ("SUBSCRIPTION_ISACTIVE" NOT NULL ENABLE);
  ALTER TABLE "CSM_REPORT_SUBS_DETAILS" MODIFY ("SUBSCRIPTION_EMAILID" NOT NULL ENABLE);
  ALTER TABLE "CSM_REPORT_SUBS_DETAILS" MODIFY ("USRLST_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_REPORT_SUBS_DETAILS" MODIFY ("SUBSCRIPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_REPORT_SUBS_DETAILS" MODIFY ("SUBSCRIPTION_DETAIL_ID" NOT NULL ENABLE);

exit;