--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_USER
--------------------------------------------------------

  CREATE TABLE "CSM_USER" 
   (	"USER_ID" NUMBER(10,0), 
	"USER_LOGIN_ID" VARCHAR2(200 BYTE), 
	"USER_FIRST_NAME" VARCHAR2(100 BYTE), 
	"USER_LAST_NAME" VARCHAR2(100 BYTE), 
	"USER_EMAIL_ADDRESS" VARCHAR2(200 BYTE), 
	"USER_ROLE" VARCHAR2(100 BYTE), 
	"USER_PASSWORD" VARCHAR2(4000 BYTE), 
	"USER_IS_LDAP_USER" NUMBER(1,0), 
	"USER_IS_ACTIVE" NUMBER(1,0), 
	"USER_ATTEMPS" NUMBER(10,0), 
	"USER_ISLOCKED" TIMESTAMP (3), 
	"USER_LOCKEDTIME" NUMBER(10,0), 
	"USER_CREATED_BY" VARCHAR2(100 BYTE), 
	"USER_CREATED_DATE" TIMESTAMP (3), 
	"USER_UPDATED_BY" VARCHAR2(100 BYTE), 
	"USER_UPDATED_DATE" TIMESTAMP (3), 
	"USER_COMMENTS" VARCHAR2(2000 BYTE), 
	"USER_IS_DELETED" NUMBER(1,0) DEFAULT (0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_USER" ON "CSM_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_USER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_USER_SEQ_TR" 
 BEFORE INSERT ON CSM_USER FOR EACH ROW
  WHEN (NEW.USER_ID IS NULL) BEGIN
 SELECT CSM_USER_seq.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_USER_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_USER
--------------------------------------------------------

  ALTER TABLE "CSM_USER" ADD CONSTRAINT "PK_CSM_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_USER" MODIFY ("USER_LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_USER" MODIFY ("USER_ID" NOT NULL ENABLE);

exit;