--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_SERVERPERFORMANCE
--------------------------------------------------------

  CREATE TABLE "CSM_SERVERPERFORMANCE" 
   (	"PER_ID" NUMBER(10,0), 
	"ENVID" NUMBER(10,0), 
	"CONFIGID" NUMBER(10,0), 
	"PER_HOSTIP" VARCHAR2(250 BYTE), 
	"PER_CPU_USAGE" BINARY_DOUBLE, 
	"PER_AVAILABLEMEMORY" BINARY_DOUBLE, 
	"PER_TOTALMEMORY" BINARY_DOUBLE, 
	"PER_CREATED_BY" VARCHAR2(100 BYTE), 
	"PER_CREATED_DATE" TIMESTAMP (3) DEFAULT (systimestamp), 
	"PER_COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_SERVERPERFORMANCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_SERVERPERFORMANCE" ON "CSM_SERVERPERFORMANCE" ("PER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_SERVERPERFORMANCE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_SERVERPERFORMANCE_SEQ_TR" 
 BEFORE INSERT ON CSM_SERVERPERFORMANCE FOR EACH ROW
  WHEN (NEW.PER_ID IS NULL) BEGIN
 SELECT CSM_SERVERPERFORMANCE_seq.NEXTVAL INTO :NEW.PER_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_SERVERPERFORMANCE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_SERVERPERFORMANCE
--------------------------------------------------------

  ALTER TABLE "CSM_SERVERPERFORMANCE" ADD CONSTRAINT "PK_CSM_SERVERPERFORMANCE" PRIMARY KEY ("PER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_SERVERPERFORMANCE" MODIFY ("PER_HOSTIP" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE" MODIFY ("CONFIGID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE" MODIFY ("ENVID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE" MODIFY ("PER_ID" NOT NULL ENABLE);

exit;