SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_SERVERPERFORMANCE_DRIVE](
	[DRIVE_ID] [int] IDENTITY(1,1) NOT NULL,
	[PER_ID] [int] NOT NULL,
	[DRIVE_NAME] [varchar](50) NULL,
	[DRIVE_LABEL] [varchar](100) NULL,
	[DRIVE_FORMAT] [varchar](50) NULL,
	[DRIVE_TYPE] [varchar](50) NULL,
	[DRIVE_FREESPACE] [float] NULL,
	[DRIVE_USEDSPACE] [float] NULL,
	[DRIVE_TOTALSPACE] [float] NULL,
	[DRIVE_CREATED_DATE] [datetime] NULL,
	[DRIVE_COMMENTS] [varchar](max) NULL,
 CONSTRAINT [PK_CSM_SERVERPERFORMANCE_DRIVE] PRIMARY KEY CLUSTERED 
(
	[DRIVE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_SERVERPERFORMANCE_DRIVE]  WITH CHECK ADD  CONSTRAINT [FK_CSM_SERVERPERFORMANCE] FOREIGN KEY([PER_ID])
REFERENCES [dbo].[CSM_SERVERPERFORMANCE] ([PER_ID])
GO

ALTER TABLE [dbo].[CSM_SERVERPERFORMANCE_DRIVE] CHECK CONSTRAINT [FK_CSM_SERVERPERFORMANCE]
GO

ALTER TABLE [dbo].[CSM_SERVERPERFORMANCE_DRIVE] ADD  DEFAULT (getdate()) FOR [DRIVE_CREATED_DATE]
GO


