
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[CSM_PORTALMONITOR](
	[PMON_ID] [int] IDENTITY(1,1) NOT NULL,
	[URL_ID] [int] NOT NULL,
	[ENV_ID] [int] NOT NULL,
	[PMON_STATUS] [varchar](20) NULL,
	[PMON_MESSAGE] [varchar](max) NULL,
	[PMON_RESPONSETIME] [int] NULL,
	[PMON_EXCEPTION] [varchar](max) NULL,
	[PMON_CREATEDBY] [varchar](100) NOT NULL,
	[PMON_CREATEDDATE] [datetime] NULL,
	[PMON_COMMENTS] [varchar](max) NULL,
 CONSTRAINT [PK_CSM_PORTALMONITOR] PRIMARY KEY CLUSTERED 
(
	[PMON_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_PORTALMONITOR] ADD  DEFAULT ('System') FOR [PMON_CREATEDBY]
GO

ALTER TABLE [dbo].[CSM_PORTALMONITOR] ADD  DEFAULT (getdate()) FOR [PMON_CREATEDDATE]
GO


