/****** Object:  Table [dbo].[CSM_ROLEMENU]    Script Date: 09/24/2015 11:22:50 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSM_ROLEMENU]') AND type in (N'U'))
DROP TABLE [dbo].[CSM_ROLEMENU]
GO


/****** Object:  Table [dbo].[CSM_ROLEMENU]    Script Date: 09/24/2015 11:22:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CSM_ROLEMENU](
	[RM_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_ID] [int] NOT NULL,
	[MENU_ID] [int] NOT NULL,
	[RM_ISACTIVE] [bit] NULL,
 CONSTRAINT [CSM_ROLE_MENU] PRIMARY KEY CLUSTERED 
(
	[RM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

