
/****** Object:  Table [dbo].[CSM_EMAIL_TRACKING]    Script Date: 2/9/2015 5:49:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[CSM_EMAIL_TRACKING](
	[EMTRAC_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENV_ID] [int] NULL,
	[Config_ID] [int] NULL,
	[EMTRAC_TO_ADDRESS] [varchar](200) NOT NULL,
	[EMTRAC_CC_ADDRESS] [varchar](200) NULL,
	[EMTRAC_BCC_ADDRESS] [varchar](200) NULL,
	[EMTRAC_SUBJECT] [varchar](500) NOT NULL,
	[EMTRAC_BODY] [varchar](5000) NULL,
	[EMTRAC_SEND_STATUS] [varchar](500) NULL,
	[EMTRAC_SEND_ERROR] [varchar](5000) NULL,
	[EMTRAC_CONTENT_TYPE] [varchar](200) NULL,
	[EMTRAC_IS_ACTIVE] [bit] NULL,
	[EMTRAC_CREATED_BY] [varchar](100) NULL,
	[EMTRAC_CREATED_DATE] [datetime] NULL,
	[EMTRAC_UPDATED_BY] [varchar](100) NULL,
	[EMTRAC_UPDATED_DATE] [datetime] NULL,
	[EMTRAC_COMMENTS] [varchar](5000) NULL,
 CONSTRAINT [PK_CSM_EMAIL_TRACKING] PRIMARY KEY CLUSTERED 
(
	[EMTRAC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


