SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_SERVERPERFORMANCE_SCHEDULE](
	[SVR_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENVID] [int] NOT NULL,
	[CONFIGID] [int] NOT NULL,
	[SVR_HOSTIP] [varchar](250) NOT NULL,
	[SVR_PORT] [varchar](10) NOT NULL,
	[SVR_LASTJOBRAN_TIME] [datetime] NULL,
	[SVR_NEXTJOBRAN_TIME] [datetime] NULL,
 CONSTRAINT [PK_CSM_SERVERPERFORMANCE_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[SVR_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_SERVERPERFORMANCE_SCHEDULE] ADD  DEFAULT (getdate()) FOR [SVR_NEXTJOBRAN_TIME]
GO


