

/****** Object:  Table [dbo].[CSM_SERVICEBUILD]    Script Date: 3/15/2015 5:52:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF OBJECT_ID('CSM_SERVICEBUILD') IS NOT NULL
	DROP TABLE CSM_SERVICEBUILD
GO

CREATE TABLE [dbo].[CSM_SERVICEBUILD](
	[BUILD_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENV_ID] [int] NOT NULL,
	[CONFIG_ID] [int] NOT NULL,
	[BUILD_DATE] [date] NULL,
	[BUILD_VERSION] [varchar](250) NULL,
	[CREATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_CSM_SERVICEBUILD] PRIMARY KEY CLUSTERED 
(
	[BUILD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


