
/****** Object:  Table [dbo].[CSM_ROLES]    Script Date: 09/24/2015 11:12:53 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSM_ROLES]') AND type in (N'U'))
DROP TABLE [dbo].[CSM_ROLES]
GO


/****** Object:  Table [dbo].[CSM_ROLES]    Script Date: 09/24/2015 11:12:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_ROLES](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_NAME] [varchar](100) NULL,
	[ROLE_DESCRIPTION] [varchar](max) NULL,
	[ROLE_TYPE] [varchar](100) NULL,
	[ROLE_ISACTIVE] [bit] NULL,
 CONSTRAINT [PK_CSM_USER_ROLES] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



