
/****** Object:  Table [dbo].[CSM_LOG]    Script Date: 2/9/2015 5:50:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF OBJECT_ID('CSM_LOG') IS NOT NULL
DROP TABLE DBO.CSM_LOG
GO

CREATE TABLE [dbo].[CSM_LOG](
	[LOGID] [int] IDENTITY(1,1) NOT NULL,
	[ENV_ID] [int] NULL,
	[SCH_ID] [int] NULL,
	[CONFIG_ID] [int] NULL,
	[LOGDESCRIPTION] [varchar](1000) NULL,
	[LOGERROR] [varchar](1000) NULL,
	[LOG_UPDATED_DATETIME] [datetime] NULL,
	[LOG_UPDATED_BY] [varchar](100) NULL,
 CONSTRAINT [PK_CSM_LOG] PRIMARY KEY CLUSTERED 
(
	[LOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


