SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE procedure [dbo].[CWT_GetAverageUsedSpace](@HOSTIP varchar(250))
As
Begin


	  SELECT pm.[DRIVE_NAME], CONVERT(float, avg(pm.[DRIVE_FREESPACE])) AVGFREESPACE, 
	  CONVERT(float, avg(pm.[DRIVE_USEDSPACE])) AVGUSEDSPACE,
	  CONVERT(float, avg(pm.[DRIVE_TOTALSPACE])) AVGTOTALSPACE,
	  DATEPART(DAY, pm.[DRIVE_CREATED_DATE]) DATERT,
	  DATEPART(MM, pm.[DRIVE_CREATED_DATE]) MONTHRT
		  from dbo.[CSM_SERVERPERFORMANCE_DRIVE] pm
		  where pm.[DRIVE_USEDSPACE] > 0
		  and pm.[DRIVE_CREATED_DATE] >= dateadd(day, -30,GETDATE())
		  and  pm.[DRIVE_CREATED_DATE] <= GETDATE()
		  and pm.[PER_ID] in (Select [PER_ID] from [dbo].[CSM_SERVERPERFORMANCE] 
		  where  [PER_HOSTIP] = @HOSTIP)
		  GROUP BY pm.[DRIVE_NAME], DATEPART(DAY, pm.[DRIVE_CREATED_DATE]), DATEPART(MM, pm.[DRIVE_CREATED_DATE])
		  order by MONTHRT, DATERT 		
 		  
	
End		 
GO


