--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_MON_DAILY_STATUS
--------------------------------------------------------

  CREATE TABLE "CSM_MON_DAILY_STATUS" 
   (	"MON_TRACK_ID" NUMBER(10,0), 
	"MON_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"MON_TRACK_DATE" TIMESTAMP (3), 
	"MON_TRACK_STATUS" VARCHAR2(200 BYTE), 
	"MON_TRACK_COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_MON_DAILY_STATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_MON_DAILY_STATUS" ON "CSM_MON_DAILY_STATUS" ("MON_TRACK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_MON_DAILY_STATUS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_MON_DAILY_STATUS_SEQ_TR" 
 BEFORE INSERT ON CSM_MON_DAILY_STATUS FOR EACH ROW
  WHEN (NEW.MON_TRACK_ID IS NULL) BEGIN
 SELECT CSM_MON_DAILY_STATUS_seq.NEXTVAL INTO :NEW.MON_TRACK_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_MON_DAILY_STATUS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_MON_DAILY_STATUS
--------------------------------------------------------

  ALTER TABLE "CSM_MON_DAILY_STATUS" ADD CONSTRAINT "PK_CSM_MON_DAILY_STATUS" PRIMARY KEY ("MON_TRACK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_MON_DAILY_STATUS" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_MON_DAILY_STATUS" MODIFY ("MON_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_MON_DAILY_STATUS" MODIFY ("MON_TRACK_ID" NOT NULL ENABLE);

exit;