--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_ROLEMENU
--------------------------------------------------------

  CREATE TABLE "CSM_ROLEMENU" 
   (	"RM_ID" NUMBER(10,0), 
	"ROLE_ID" NUMBER(10,0), 
	"MENU_ID" NUMBER(10,0), 
	"RM_ISACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CSM_ROLE_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSM_ROLE_MENU" ON "CSM_ROLEMENU" ("RM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_ROLEMENU_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_ROLEMENU_SEQ_TR" 
 BEFORE INSERT ON CSM_ROLEMENU FOR EACH ROW
  WHEN (NEW.RM_ID IS NULL) BEGIN
 SELECT CSM_ROLEMENU_seq.NEXTVAL INTO :NEW.RM_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_ROLEMENU_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_ROLEMENU
--------------------------------------------------------

  ALTER TABLE "CSM_ROLEMENU" ADD CONSTRAINT "CSM_ROLE_MENU" PRIMARY KEY ("RM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_ROLEMENU" MODIFY ("MENU_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_ROLEMENU" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_ROLEMENU" MODIFY ("RM_ID" NOT NULL ENABLE);

exit;