--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "CSM_SCHEDULE" 
   (	"SCH_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONGIG_ID" NUMBER(10,0), 
	"SCH_INTERVAL" NUMBER(10,0), 
	"SCH_DURATION" VARCHAR2(100 BYTE), 
	"SCH_REPEATS" VARCHAR2(100 BYTE), 
	"SCH_STARTBY" TIMESTAMP (3), 
	"SCH_ENDAS" VARCHAR2(100 BYTE), 
	"SCH_END_OCCURANCE" NUMBER(10,0), 
	"SCH_ENDBY" TIMESTAMP (3), 
	"SCH_IS_ACTIVE" NUMBER(1,0), 
	"SCH_LASTJOBRAN_TIME" TIMESTAMP (3), 
	"SCH_NEXTJOBRAN_TIME" TIMESTAMP (3), 
	"SCH_CREATED_BY" VARCHAR2(100 BYTE), 
	"SCH_CREATED_DATE" TIMESTAMP (3), 
	"SCH_UPDATED_BY" VARCHAR2(100 BYTE), 
	"SCH_UPDATED_DATE" TIMESTAMP (3), 
	"SCH_COMMENTS" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_SCHEDULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_SCHEDULE" ON "CSM_SCHEDULE" ("SCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_SCHEDULE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_SCHEDULE_SEQ_TR" 
 BEFORE INSERT ON CSM_SCHEDULE FOR EACH ROW
  WHEN (NEW.SCH_ID IS NULL) BEGIN
 SELECT CSM_SCHEDULE_seq.NEXTVAL INTO :NEW.SCH_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_SCHEDULE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "CSM_SCHEDULE" ADD CONSTRAINT "PK_CSM_SCHEDULE" PRIMARY KEY ("SCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_SCHEDULE" MODIFY ("SCH_IS_ACTIVE" NOT NULL ENABLE);
  --ALTER TABLE "CSM_SCHEDULE" MODIFY ("SCH_REPEATS" NOT NULL ENABLE);
  ALTER TABLE "CSM_SCHEDULE" MODIFY ("SCH_DURATION" NOT NULL ENABLE);
  ALTER TABLE "CSM_SCHEDULE" MODIFY ("SCH_INTERVAL" NOT NULL ENABLE);
  ALTER TABLE "CSM_SCHEDULE" MODIFY ("CONGIG_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SCHEDULE" MODIFY ("ENV_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SCHEDULE" MODIFY ("SCH_ID" NOT NULL ENABLE);

exit;