--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_SERVERPERFORMANCE_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "CSM_SERVERPERFORMANCE_SCHEDULE" 
   (	"SVR_ID" NUMBER(10,0), 
	"ENVID" NUMBER(10,0), 
	"CONFIGID" NUMBER(10,0), 
	"SVR_HOSTIP" VARCHAR2(250 BYTE), 
	"SVR_PORT" VARCHAR2(10 BYTE), 
	"SVR_LASTJOBRAN_TIME" TIMESTAMP (3), 
	"SVR_NEXTJOBRAN_TIME" TIMESTAMP (3) DEFAULT (systimestamp)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_SP_SCHEDULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_SP_SCHEDULE" ON "CSM_SERVERPERFORMANCE_SCHEDULE" ("SVR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_SP_SCHEDULE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_SP_SCHEDULE_SEQ_TR" 
 BEFORE INSERT ON CSM_SERVERPERFORMANCE_SCHEDULE FOR EACH ROW
  WHEN (NEW.SVR_ID IS NULL) BEGIN
 SELECT CSM_SP_SCHEDULE_seq.NEXTVAL INTO :NEW.SVR_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_SP_SCHEDULE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_SERVERPERFORMANCE_SCHEDULE
--------------------------------------------------------

  ALTER TABLE "CSM_SERVERPERFORMANCE_SCHEDULE" ADD CONSTRAINT "PK_CSM_SP_SCHEDULE" PRIMARY KEY ("SVR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_SERVERPERFORMANCE_SCHEDULE" MODIFY ("SVR_PORT" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE_SCHEDULE" MODIFY ("SVR_HOSTIP" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE_SCHEDULE" MODIFY ("CONFIGID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE_SCHEDULE" MODIFY ("ENVID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE_SCHEDULE" MODIFY ("SVR_ID" NOT NULL ENABLE);

exit;