--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_SERVICEBUILD
--------------------------------------------------------

  CREATE TABLE "CSM_SERVICEBUILD" 
   (	"BUILD_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"CONFIG_ID" NUMBER(10,0), 
	"BUILD_DATE" DATE, 
	"BUILD_VERSION" VARCHAR2(250 BYTE), 
	"CREATED_DATE" TIMESTAMP (3)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_SERVICEBUILD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_SERVICEBUILD" ON "CSM_SERVICEBUILD" ("BUILD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_SERVICEBUILD_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_SERVICEBUILD_SEQ_TR" 
 BEFORE INSERT ON CSM_SERVICEBUILD FOR EACH ROW
  WHEN (NEW.BUILD_ID IS NULL) BEGIN
 SELECT CSM_SERVICEBUILD_seq.NEXTVAL INTO :NEW.BUILD_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_SERVICEBUILD_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_SERVICEBUILD
--------------------------------------------------------

  ALTER TABLE "CSM_SERVICEBUILD" ADD CONSTRAINT "PK_CSM_SERVICEBUILD" PRIMARY KEY ("BUILD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_SERVICEBUILD" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVICEBUILD" MODIFY ("ENV_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVICEBUILD" MODIFY ("BUILD_ID" NOT NULL ENABLE);

exit;