--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_SERVERPERFORMANCE_DRIVE
--------------------------------------------------------

  CREATE TABLE "CSM_SERVERPERFORMANCE_DRIVE" 
   (	"DRIVE_ID" NUMBER(10,0), 
	"PER_ID" NUMBER(10,0), 
	"DRIVE_NAME" VARCHAR2(50 BYTE), 
	"DRIVE_LABEL" VARCHAR2(100 BYTE), 
	"DRIVE_FORMAT" VARCHAR2(50 BYTE), 
	"DRIVE_TYPE" VARCHAR2(50 BYTE), 
	"DRIVE_FREESPACE" BINARY_DOUBLE, 
	"DRIVE_USEDSPACE" BINARY_DOUBLE, 
	"DRIVE_TOTALSPACE" BINARY_DOUBLE, 
	"DRIVE_CREATED_DATE" TIMESTAMP (3) DEFAULT (systimestamp), 
	"DRIVE_COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_SERVERPERFORMANCE_DRIVE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_SERVERPERFORMANCE_DRIVE" ON "CSM_SERVERPERFORMANCE_DRIVE" ("DRIVE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_SP_DRIVE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_SP_DRIVE_SEQ_TR" 
 BEFORE INSERT ON CSM_SERVERPERFORMANCE_DRIVE FOR EACH ROW
  WHEN (NEW.DRIVE_ID IS NULL) BEGIN
 SELECT CSM_SP_DRIVE_seq.NEXTVAL INTO :NEW.DRIVE_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_SP_DRIVE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_SERVERPERFORMANCE_DRIVE
--------------------------------------------------------

  ALTER TABLE "CSM_SERVERPERFORMANCE_DRIVE" ADD CONSTRAINT "PK_CSM_SERVERPERFORMANCE_DRIVE" PRIMARY KEY ("DRIVE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_SERVERPERFORMANCE_DRIVE" MODIFY ("PER_ID" NOT NULL ENABLE);
  ALTER TABLE "CSM_SERVERPERFORMANCE_DRIVE" MODIFY ("DRIVE_ID" NOT NULL ENABLE);

exit;