--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_GROUP
--------------------------------------------------------

  CREATE TABLE "CSM_GROUP" 
   (	"GROUP_ID" NUMBER(10,0), 
	"GROUP_NAME" VARCHAR2(200 BYTE), 
	"GROUP_CREATED_BY" VARCHAR2(100 BYTE), 
	"GROUP_CREATED_DATE" TIMESTAMP (3), 
	"GROUP_UPDATED_BY" VARCHAR2(100 BYTE), 
	"GROUP_UPDATED_DATE" TIMESTAMP (3), 
	"GROUP_COMMENTS" VARCHAR2(2000 BYTE), 
	"GROUP_IS_ACTIVE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_GROUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_GROUP" ON "CSM_GROUP" ("GROUP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_GROUP_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_GROUP_SEQ_TR" 
 BEFORE INSERT ON CSM_GROUP FOR EACH ROW
  WHEN (NEW.GROUP_ID IS NULL) BEGIN
 SELECT CSM_GROUP_seq.NEXTVAL INTO :NEW.GROUP_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_GROUP_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_GROUP
--------------------------------------------------------

  ALTER TABLE "CSM_GROUP" ADD CONSTRAINT "PK_CSM_GROUP" PRIMARY KEY ("GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_GROUP" MODIFY ("GROUP_ID" NOT NULL ENABLE);

exit;