--------------------------------------------------------
--  File created - Monday-March-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSM_EMAIL_USERLIST
--------------------------------------------------------

  CREATE TABLE "CSM_EMAIL_USERLIST" 
   (	"USRLST_ID" NUMBER(10,0), 
	"ENV_ID" NUMBER(10,0), 
	"USRLST_EMAIL_ADDRESS" VARCHAR2(100 BYTE), 
	"USRLST_TYPE" VARCHAR2(100 BYTE), 
	"USRLST_IS_ACTIVE" NUMBER(1,0), 
	"USRLST_CREATED_BY" VARCHAR2(100 BYTE), 
	"USRLST_CREATED_DATE" TIMESTAMP (3), 
	"USRLST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"USRLST_UPDATED_DATE" TIMESTAMP (3), 
	"USRLST_COMMENTS" VARCHAR2(2000 BYTE), 
	"USRLST_MESSAGETYPE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CSM_EMAIL_USERLIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CSM_EMAIL_USERLIST" ON "CSM_EMAIL_USERLIST" ("USRLST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CSM_EMAIL_USERLIST_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSM_EMAIL_USERLIST_SEQ_TR" 
 BEFORE INSERT ON CSM_EMAIL_USERLIST FOR EACH ROW
  WHEN (NEW.USRLST_ID IS NULL) BEGIN
 SELECT CSM_EMAIL_USERLIST_seq.NEXTVAL INTO :NEW.USRLST_ID FROM DUAL;
END;

/
ALTER TRIGGER "CSM_EMAIL_USERLIST_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table CSM_EMAIL_USERLIST
--------------------------------------------------------

  ALTER TABLE "CSM_EMAIL_USERLIST" ADD CONSTRAINT "PK_CSM_EMAIL_USERLIST" PRIMARY KEY ("USRLST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CSM_EMAIL_USERLIST" MODIFY ("USRLST_EMAIL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "CSM_EMAIL_USERLIST" MODIFY ("USRLST_ID" NOT NULL ENABLE);

exit;