/****** Object:  Table [dbo].[CSM_GROUP_SCHEDULE_DETAIL]    Script Date: 10/04/2015 14:16:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_GROUP_SCHEDULE_DETAIL](
	[GROUP_SERVICE_SCH_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_SCH_ID] [int] NULL,
	[GROUP_ID] [int] NULL,
	[ENV_ID] [int] NULL,
	[CONFIG_ID] [int] NULL,
	[GROUP_SCH_ISACTIVE] [bit] NULL,
	[GROUP_SCH_STATUS] [nchar](20) NULL,
	[GROUP_SCH_UPDATEDTIME] [datetime] default GETDATE(),
	[GROUP_SCH_RESULT] [varchar](50) NULL,
	[GROUP_SCH_SERVICE_STARTTIME] [datetime] NULL,
	[GROUP_SCH_SERVICE_COMPLETEDTIME] [datetime] NULL,
 CONSTRAINT [PK_CSM_GROUP_SCHEDULE_DETAIL] PRIMARY KEY CLUSTERED 
(
	[GROUP_SERVICE_SCH_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'whether this entry is active or NOT' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CSM_GROUP_SCHEDULE_DETAIL', @level2type=N'COLUMN',@level2name=N'GROUP_SCH_ISACTIVE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'store values like C-Completed, F-Failed, O-Open, P-Processing' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CSM_GROUP_SCHEDULE_DETAIL', @level2type=N'COLUMN',@level2name=N'GROUP_SCH_STATUS'
GO

ALTER TABLE [dbo].[CSM_GROUP_SCHEDULE_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_SCH_ID] FOREIGN KEY([GROUP_SCH_ID])
REFERENCES [dbo].[CSM_GROUP_SCHEDULE] ([GROUP_SCH_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CSM_GROUP_SCHEDULE_DETAIL] CHECK CONSTRAINT [FK_GROUP_SCH_ID]
GO


