
/****** Object:  Table [dbo].[CSM_USER_ROLE]    Script Date: 09/24/2015 11:08:41 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSM_USER_ROLE]') AND type in (N'U'))
DROP TABLE [dbo].[CSM_USER_ROLE]
GO


/****** Object:  Table [dbo].[CSM_USER_ROLE]    Script Date: 09/24/2015 11:08:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_USER_ROLE](
	[USER_ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[ROLE_ID] [int] NOT NULL,
	[USER_ROLE_ISACTIVE] [bit] NULL,
	[USER_CREATED_BY] [varchar](100) NULL,
	[USER_CREATED_DATE] [datetime] NULL,
	[USER_UPDATED_BY] [varchar](100) NULL,
	[USER_UPDATED_DATE] [datetime] NULL,
	[USER_COMMENTS] [varchar](2000) NULL,
 CONSTRAINT [PK_CSM_USER_ROLE] PRIMARY KEY CLUSTERED 
(
	[USER_ROLE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
