/****** Object:  Table [dbo].[CSM_MON_DAILY_STATUS]    Script Date: 10/12/2015 15:59:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_MON_DAILY_STATUS](
	[MON_TRACK_ID] [int] IDENTITY(1,1) NOT NULL,
	[MON_ID] [int] NOT NULL,
	[CONFIG_ID] [int] NOT NULL,
	[ENV_ID] [int] NULL,
	[MON_TRACK_DATE] [datetime] NULL,
	[MON_TRACK_STATUS] [varchar](200) NULL,
	[MON_TRACK_COMMENTS] [varchar](max) NULL,
 CONSTRAINT [PK_CSM_MON_DAILY_STATUS] PRIMARY KEY CLUSTERED 
(
	[MON_TRACK_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


