SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_URLCONFIGURATION](
	[URL_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENV_ID] [int] NOT NULL,
	[URL_TYPE] [varchar](50) NOT NULL,
	[URL_ADDRESS] [varchar](500) NOT NULL,
	[URL_DISPLAYNAME] [varchar](500) NULL,
	[URL_MATCHCONTENT] [varchar](500) NULL,
	[URL_INTERVAL] [int] NULL,
	[URL_USERNAME] [varchar](500) NULL,
	[URL_PASSWORD] [varchar](500) NULL,
	[URL_STATUS] [bit] NULL,
	[URL_ISACTIVE] [bit] NULL,
	[URL_CREATEDBY] [varchar](100) NOT NULL,
	[URL_CREATEDDATE] [datetime] NULL,
	[URL_UPDATEDBY] [varchar](100) NULL,
	[URL_UPDATEDDATE] [datetime] NULL,
	[URL_COMMENTS] [varchar](max) NULL,
	[URL_LASTJOBRUNTIME] [datetime] NULL,
	[URL_NEXTJOBRUNTIME] [datetime] NULL,
 CONSTRAINT [PK_CSM_URLCONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[URL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_URLCONFIGURATION] ADD  DEFAULT ('True') FOR [URL_STATUS]
GO

ALTER TABLE [dbo].[CSM_URLCONFIGURATION] ADD  DEFAULT ('True') FOR [URL_ISACTIVE]
GO

ALTER TABLE [dbo].[CSM_URLCONFIGURATION] ADD  DEFAULT (getdate()) FOR [URL_CREATEDDATE]
GO

ALTER TABLE [dbo].[CSM_URLCONFIGURATION] ADD  DEFAULT (getdate()) FOR [URL_NEXTJOBRUNTIME]
GO


