
/****** Object:  Table [dbo].[CSM_INCIDENT]    Script Date: 2/9/2015 5:50:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
IF OBJECT_ID('CSM_INCIDENT') IS NOT NULL
DROP TABLE DBO.CSM_INCIDENT
GO

CREATE TABLE [dbo].[CSM_INCIDENT](
	[TRK_ID] [int] IDENTITY(1,1) NOT NULL,
	[MON_ID] [int] NOT NULL,
	[ENV_ID] [int] NULL,
	[CONFIG_ID] [int] NOT NULL,
	[TRK_ISSUE] [varchar](max) NULL,
	[TRK_SOLUTION] [varchar](max) NULL,
	[TRK_CREATED_BY] [varchar](100) NULL,
	[TRK_CREATED_DATE] [datetime] NULL,
	[TRK_UPDATED_BY] [varchar](100) NULL,
	[TRK_UPDATED_DATE] [datetime] NULL,
	[TRK_COMMENTS] [varchar](2000) NULL,
 CONSTRAINT [PK_CSM_INCIDENT] PRIMARY KEY CLUSTERED 
(
	[TRK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


