
/****** Object:  Table [dbo].[CSM_EMAIL_CONFIGURATION]    Script Date: 2/9/2015 5:49:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_EMAIL_CONFIGURATION](
	[EMAIL_SERVER_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMAIL_SERVER_NAME] [varchar](100) NOT NULL,
	[EMAIL_SERVER_IPADDRESS] [varchar](100) NOT NULL,
	[EMAIL_SERVER_PORT] [varchar](100) NOT NULL,
	[EMAIL_AUTH_USER_ID] [varchar](100) NOT NULL,
	[EMAIL_AUTH_USER_PWD] [varchar](100) NULL,
	[EMAIL_DEFAULT_SENDER] [varchar](100) NULL,
	[EMAIL_IS_ACTIVE] [bit] NOT NULL,
	[EMAIL_CREATED_BY] [varchar](100) NULL,
	[EMAIL_CREATED_DATE] [datetime] NULL,
	[EMAIL_UPDATED_BY] [varchar](100) NULL,
	[EMAIL_UPDATED_DATE] [datetime] NULL,
	[EMAIL_COMMENTS] [varchar](2000) NULL,
	[EMAIL_SSL_ENABLE] [bit] NULL,
	[EMAIL_ADMIN_MAILADRESS] [varchar](100) NULL,
 CONSTRAINT [PK_CSM_EMAIL_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[EMAIL_SERVER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


