/****** Object:  Table [dbo].[CSM_GROUP]    Script Date: 06/26/2015 14:12:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO



CREATE TABLE [dbo].[CSM_GROUP](
	[GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_NAME] [varchar](200) NULL,
	[GROUP_CREATED_BY] [varchar](100) NULL,
	[GROUP_CREATED_DATE] [datetime] NULL,
	[GROUP_UPDATED_BY] [varchar](100) NULL,
	[GROUP_UPDATED_DATE] [datetime] NULL,
	[GROUP_COMMENTS] [varchar](2000) NULL,
	[GROUP_IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CSM_GROUP] PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


