/****** Object:  Table [dbo].[CSM_GROUP_DETAIL]    Script Date: 06/26/2015 14:14:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO



CREATE TABLE [dbo].[CSM_GROUP_DETAIL](
	[GROUP_DETAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[GROUP_ID] [int] NOT NULL,
	[ENV_ID] [int] NOT NULL,
	[CONFIG_ID] [int] NOT NULL,
	[WIN_SERVICE_ID] [int] NULL,
	[GROUP_CREATED_BY] [varchar](100) NULL,
	[GROUP_CREATED_DATE] [datetime] NULL,
	[GROUP_UPDATED_BY] [varchar](100) NULL,
	[GROUP_UPDATED_DATE] [datetime] NULL,
	[GROUP_DETAIL_COMMENTS] [varchar](2000) NULL,
	[GROUP_ISACTIVE] [bit] NULL,
 CONSTRAINT [PK_CSM_GROUP_DETAIL] PRIMARY KEY CLUSTERED 
(
	[GROUP_DETAIL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_GROUP_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_GROUP_ID] FOREIGN KEY([GROUP_ID])
REFERENCES [dbo].[CSM_GROUP] ([GROUP_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CSM_GROUP_DETAIL] CHECK CONSTRAINT [FK_GROUP_ID]
GO


