
/****** Object:  Table [dbo].[CSM_CONFIGURATION]    Script Date: 2/9/2015 5:49:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


CREATE TABLE [dbo].[CSM_CONFIGURATION](
	[CONFIG_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENV_ID] [int] NULL,
	[CONFIG_SERVICE_TYPE] [varchar](30) NOT NULL,
	[CONFIG_PORT_NUMBER] [varchar](10) NOT NULL,
	[CONFIG_URL_ADDRESS] [varchar](500) NOT NULL,
	[CONFIG_DESCRIPTION] [varchar](500) NULL,
	[CONFIG_IS_VALIDATED] [bit] NOT NULL,
	[CONFIG_IS_ACTIVE] [bit] NOT NULL,
	[CONFIG_IS_MONITORED] [bit] NOT NULL,
	[CONFIG_IS_LOCKED] [bit] NOT NULL,
	[CONFIG_CREATED_BY] [varchar](100) NULL,
	[CONFIG_CREATED_DATE] [datetime] NULL,
	[CONFIG_UPDATED_BY] [varchar](100) NULL,
	[CONFIG_UPDATED_DATE] [datetime] NULL,
	[CONFIG_COMMENTS] [varchar](2000) NULL,
	[CONFIG_HOST_IP] [varchar](100) NULL DEFAULT ('10.12.110.111'),
	[CONFIG_MAIL_FREQ] [int] NULL,
	[CONFIG_LOCATION] [varchar](200) NULL,
	[CONFIG_ISCONSOLIDATED] [bit] NULL,
	[CONFIG_ISNOTIFY] [bit] NULL,
	[CONFIG_ISPRIMARY] [bit] NULL,
	[CONFIG_REF_ID] [int] NULL,
	[CONFIG_ISNOTIFY_MAIN] [bit] NULL,
	[CONFIG_COLUMN1] [varchar](100) NULL,
	[CONFIG_COLUMN2] [varchar](100) NULL,
	[CONFIG_COLUMN3] [varchar](100) NULL,
	[CONFIG_COLUMN4] [varchar](100) NULL,
	[CONFIG_COLUMN5] [varchar](100) NULL,
 CONSTRAINT [PK_CSM_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[CONFIG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_CONFIGURATION]  WITH CHECK ADD  CONSTRAINT [FK_Conf_EnvID] FOREIGN KEY([ENV_ID])
REFERENCES [dbo].[CSM_ENVIRONEMENT] ([ENV_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CSM_CONFIGURATION] CHECK CONSTRAINT [FK_Conf_EnvID]
GO


