SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_POERSONALIZE](
	[PERS_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL,
	[PERS_DB_REFRESHTIME] [int] NULL,
	[PERS_ISACTIVE] [bit] NULL,
	[PERS_CREATEDDATE] [datetime] NULL,
	[PERS_CREATEDBY] [varchar](10) NULL,
	[PERS_UPDATEDDATE] [datetime] NULL,
	[PERS_UPDATEDBY] [varchar](10) NULL,
	[PERS_FUTURE_COL_1] [varchar](100) NULL,
	[PERS_FUTURE_COL_2] [varchar](100) NULL,
	[PERS_FUTURE_COL_3] [varchar](100) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


