/****** Object:  Table [dbo].[CSM_MENUS]    Script Date: 09/23/2015 21:37:04 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSM_MENUS]') AND type in (N'U'))
DROP TABLE [dbo].[CSM_MENUS]
GO

/****** Object:  Table [dbo].[CSM_MENUS]    Script Date: 09/23/2015 21:37:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_MENUS](
	[MENU_ID] [int] IDENTITY(1,1) NOT NULL,
	[MENU_MAIN] [varchar](100) NOT NULL,
	[MENU_SUB] [varchar](100) NOT NULL,
	[MENU_PATH] [varchar](100) NOT NULL,
	[MENU_ISPOPUP] [bit] NULL,
	[MENU_ISACTIVE] [bit] NULL,
	[MENU_MAIN_ORDER] [int] NULL,
	[MENU_SUB_ORDER] [int] NULL,
	[MENU_COMMENTS] [int] NULL,
 CONSTRAINT [PK_CSM_MENUS] PRIMARY KEY CLUSTERED 
(
	[MENU_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


