
/****** Object:  Table [dbo].[CSM_SCHEDULE]    Script Date: 2/9/2015 5:51:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
IF OBJECT_ID('CSM_SCHEDULE') IS NOT NULL
DROP TABLE DBO.CSM_SCHEDULE
GO

CREATE TABLE [dbo].[CSM_SCHEDULE](
	[SCH_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENV_ID] [int] NOT NULL,
	[CONGIG_ID] [int] NOT NULL,
	[SCH_INTERVAL] [int] NOT NULL,
	[SCH_DURATION] [varchar](100) NOT NULL,
	[SCH_REPEATS] [varchar](100) NOT NULL,
	[SCH_STARTBY] [datetime] NULL,
	[SCH_ENDAS] [varchar](100) NULL,
	[SCH_END_OCCURANCE] [int] NULL,
	[SCH_ENDBY] [datetime] NULL,
	[SCH_IS_ACTIVE] [bit] NOT NULL,
	[SCH_LASTJOBRAN_TIME] [datetime] NULL,
	[SCH_NEXTJOBRAN_TIME] [datetime] NULL,
	[SCH_CREATED_BY] [varchar](100) NULL,
	[SCH_CREATED_DATE] [datetime] NULL,
	[SCH_UPDATED_BY] [varchar](100) NULL,
	[SCH_UPDATED_DATE] [datetime] NULL,
	[SCH_COMMENTS] [varchar](2000) NULL,
 CONSTRAINT [PK_CSM_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[SCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_Sche_EnvID] FOREIGN KEY([ENV_ID])
REFERENCES [dbo].[CSM_ENVIRONEMENT] ([ENV_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CSM_SCHEDULE] CHECK CONSTRAINT [FK_Sche_EnvID]
GO


