

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CSM_REPORT_SUBSCRIPTION_ID]') AND parent_object_id = OBJECT_ID(N'[dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]'))
ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS] DROP CONSTRAINT [FK_CSM_REPORT_SUBSCRIPTION_ID]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CSM_REPORT_USERLST_ID]') AND parent_object_id = OBJECT_ID(N'[dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]'))
ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS] DROP CONSTRAINT [FK_CSM_REPORT_USERLST_ID]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__CSM_REPOR__SUBSC__1D9B5BB6]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS] DROP CONSTRAINT [DF__CSM_REPOR__SUBSC__1D9B5BB6]
END

GO


/****** Object:  Table [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]    Script Date: 09/13/2016 21:41:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]') AND type in (N'U'))
DROP TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]
GO



/****** Object:  Table [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]    Script Date: 09/13/2016 21:41:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS](
	[SUBSCRIPTION_DETAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBSCRIPTION_ID] [int] NOT NULL,
	[USRLST_ID] [int] NOT NULL,
	[SUBSCRIPTION_EMAILID] [varchar](100) NOT NULL,
	[SUBSCRIPTION_ISACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_REPORT_SUBSCRIPTION_DETAILS] PRIMARY KEY CLUSTERED 
(
	[SUBSCRIPTION_DETAIL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_CSM_REPORT_SUBSCRIPTION_ID] FOREIGN KEY([SUBSCRIPTION_ID])
REFERENCES [dbo].[CSM_REPORT_SUBSCRIPTION] ([SUBSCRIPTION_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS] CHECK CONSTRAINT [FK_CSM_REPORT_SUBSCRIPTION_ID]
GO

ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_CSM_REPORT_USERLST_ID] FOREIGN KEY([USRLST_ID])
REFERENCES [dbo].[CSM_EMAIL_USERLIST] ([USRLST_ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS] CHECK CONSTRAINT [FK_CSM_REPORT_USERLST_ID]
GO

ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION_DETAILS] ADD  DEFAULT ('True') FOR [SUBSCRIPTION_ISACTIVE]
GO


