
/****** Object:  Table [dbo].[CSM_LDAP_CONFIGURATION]    Script Date: 2/9/2015 5:50:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
IF OBJECT_ID('CSM_LDAP_CONFIGURATION') IS NOT NULL
DROP TABLE DBO.CSM_LDAP_CONFIGURATION
GO

CREATE TABLE [dbo].[CSM_LDAP_CONFIGURATION](
	[LDAP_ID] [int] IDENTITY(1,1) NOT NULL,
	[LDAP_SERVER_NAME] [varchar](100) NOT NULL,
	[LDAP_AUTH_USER_ID] [varchar](100) NOT NULL,
	[LDAP_AUTH_USER_PWD] [varchar](100) NULL,
	[LDAP_IS_ACTIVE] [bit] NOT NULL,
	[LDAP_CREATED_BY] [varchar](100) NULL,
	[LDAP_CREATED_DATE] [datetime] NULL,
	[LDAP_UPDATED_BY] [varchar](100) NULL,
	[LDAP_UPDATED_DATE] [datetime] NULL,
	[LDAP_COMMENTS] [varchar](2000) NULL,
 CONSTRAINT [PK_CSM_LDAP_CONFIGURATION] PRIMARY KEY CLUSTERED 
(
	[LDAP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


