
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF__CSM_REPOR__SUBSC__0A888742]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION] DROP CONSTRAINT [DF__CSM_REPOR__SUBSC__0A888742]
END

GO


/****** Object:  Table [dbo].[CSM_REPORT_SUBSCRIPTION]    Script Date: 09/13/2016 21:39:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CSM_REPORT_SUBSCRIPTION]') AND type in (N'U'))
DROP TABLE [dbo].[CSM_REPORT_SUBSCRIPTION]
GO

/****** Object:  Table [dbo].[CSM_REPORT_SUBSCRIPTION]    Script Date: 09/13/2016 21:39:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSM_REPORT_SUBSCRIPTION](
	[SUBSCRIPTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBSCRIPTION_TYPE] [varchar](100) NOT NULL,
	[SUBSCRIPTION_TIME] [varchar](100) NOT NULL,
	[SUBSCRIPTION_ISACTIVE] [bit] NOT NULL,
	[CREATED_BY] [varchar](100) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [varchar](100) NULL,
	[UPDATED_DATE] [datetime] NULL,
	[SCH_LASTJOBRAN_TIME] [datetime] NULL,
	[SCH_NEXTJOBRAN_TIME] [datetime] NULL,
 CONSTRAINT [PK_REPORT_SUBSCRIPTION] PRIMARY KEY CLUSTERED 
(
	[SUBSCRIPTION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CSM_REPORT_SUBSCRIPTION] ADD  DEFAULT ('True') FOR [SUBSCRIPTION_ISACTIVE]
GO


