/****** Object:  Table [dbo].[CSM_WINDOWS_SERVICES]    Script Date: 06/26/2015 14:15:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF OBJECT_ID('CSM_WINDOWS_SERVICES') IS NOT NULL
DROP TABLE DBO.CSM_WINDOWS_SERVICES
GO

CREATE TABLE [dbo].[CSM_WINDOWS_SERVICES](
	[WIN_SERVICE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ENV_ID] [int] NOT NULL,
	[CONFIG_ID] [int] NOT NULL,
	[WIN_SERVICENAME] [varchar](200) NULL,
	[WIN_COMMENTS] [varchar](2000) NULL,
	[WIN_CREATED_BY] [varchar](100) NULL,
	[WIN_CREATED_DATE] [datetime] NULL,
	[WIN_UPDATED_BY] [varchar](100) NULL,
	[WIN_UPDATED_DATE] [datetime] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


