SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[CWT_GetMailServerDetail] As
BEGIN
	SELECT [EMAIL_SERVER_ID]
		  ,[EMAIL_SERVER_NAME]
		  ,[EMAIL_SERVER_IPADDRESS]
		  ,[EMAIL_SERVER_PORT]
		  ,[EMAIL_AUTH_USER_ID]
		  ,[EMAIL_AUTH_USER_PWD]
		  ,[EMAIL_DEFAULT_SENDER]
		  ,[EMAIL_IS_ACTIVE]
		  ,[EMAIL_CREATED_BY]
		  ,[EMAIL_CREATED_DATE]
		  ,[EMAIL_UPDATED_BY]
		  ,[EMAIL_UPDATED_DATE]
		  ,[EMAIL_COMMENTS]
		  ,[EMAIL_SSL_ENABLE]
		  ,[EMAIL_ADMIN_MAILADRESS]
	  FROM [dbo].[CSM_EMAIL_CONFIGURATION]
  END
GO


