/****** Object:  StoredProcedure [dbo].[CWT_GetEnvironmentConfigList]    Script Date: 08/23/2015 19:01:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[CWT_GetEnvironmentConfigList]
(
      @CONFIG_ID int,
      @ENV_ID int
)
as
Begin
	if(@CONFIG_ID>0 and @CONFIG_ID is not null)
	Begin
		select 
	   [CONFIG_ID]
      ,[CSM_CONFIGURATION].[ENV_ID]
      ,[CSM_ENVIRONEMENT].ENV_NAME
      ,[CONFIG_SERVICE_TYPE]
      ,[CONFIG_PORT_NUMBER]
      ,[CONFIG_URL_ADDRESS]
      ,[CONFIG_DESCRIPTION]
      ,[CONFIG_IS_VALIDATED]
      ,[CONFIG_IS_ACTIVE]
      ,[CONFIG_IS_MONITORED]
      ,[CONFIG_IS_LOCKED]
      ,[CONFIG_CREATED_BY]
      ,[CONFIG_CREATED_DATE]
      ,[CONFIG_UPDATED_BY]
      ,[CONFIG_UPDATED_DATE]
      ,[CONFIG_COMMENTS]
      ,[CONFIG_HOST_IP]
      ,[CONFIG_MAIL_FREQ]
      ,[CONFIG_LOCATION]
      ,[CONFIG_ISCONSOLIDATED]
      ,[CONFIG_ISNOTIFY]
	  ,[CONFIG_ISPRIMARY]
	  ,[CONFIG_REF_ID]
	  ,[CSM_SCHEDULE].SCH_ID
	  ,[CSM_SCHEDULE].SCH_COMMENTS
	  ,(Select WIN_SERVICENAME from CSM_WINDOWS_SERVICES win where win.CONFIG_ID = [CSM_CONFIGURATION].CONFIG_ID) WIN_SERVICENAME
	  ,(Select WIN_SERVICE_ID from CSM_WINDOWS_SERVICES win where win.CONFIG_ID = [CSM_CONFIGURATION].CONFIG_ID) WIN_SERVICE_ID
	  ,usr.USER_FIRST_NAME USERFIRSTNAME
	  ,usr.USER_LAST_NAME USERLASTNAME
      from [CSM_CONFIGURATION] 
      inner join [CSM_ENVIRONEMENT] on
		[CSM_CONFIGURATION].[ENV_ID] = [CSM_ENVIRONEMENT].[ENV_ID]
	  left outer join CSM_SCHEDULE on CSM_SCHEDULE.ENV_ID = [CSM_ENVIRONEMENT].[ENV_ID]
		  and  CSM_SCHEDULE.ENV_ID = [CSM_CONFIGURATION].[ENV_ID]
		  and CSM_SCHEDULE.CONGIG_ID =  [CSM_CONFIGURATION].CONFIG_ID
		  and CSM_SCHEDULE.SCH_ENDBY >= GETDATE()
	  join dbo.CSM_USER usr on usr.USER_ID = [CONFIG_CREATED_BY]
	  where [CONFIG_IS_ACTIVE] = 'True' and
		[CSM_CONFIGURATION].[CONFIG_ISPRIMARY] = 'True' 
		and	[CONFIG_ID] = @CONFIG_ID

	End
	else
	Begin
		if(@ENV_ID is not null and @ENV_ID>0)
		Begin
			select 
			   [CONFIG_ID]
			  ,[CSM_CONFIGURATION].[ENV_ID]
			  ,[CSM_ENVIRONEMENT].ENV_NAME
			  ,[CONFIG_SERVICE_TYPE]
			  ,[CONFIG_PORT_NUMBER]
			  ,[CONFIG_URL_ADDRESS]
			  ,[CONFIG_DESCRIPTION]
			  ,[CONFIG_IS_VALIDATED]
			  ,[CONFIG_IS_ACTIVE]
			  ,[CONFIG_IS_MONITORED]
			  ,[CONFIG_IS_LOCKED]
			  ,[CONFIG_CREATED_BY]
			  ,[CONFIG_CREATED_DATE]
			  ,[CONFIG_UPDATED_BY]
			  ,[CONFIG_UPDATED_DATE]
			  ,[CONFIG_COMMENTS]
			  ,[CONFIG_HOST_IP]
			  ,[CONFIG_MAIL_FREQ]
			  ,[CONFIG_LOCATION]
			  ,[CONFIG_ISCONSOLIDATED]
			  ,[CONFIG_ISNOTIFY]
			  ,[CONFIG_ISPRIMARY]
			  ,[CONFIG_REF_ID]
			  ,[CSM_SCHEDULE].SCH_ID
			  ,[CSM_SCHEDULE].SCH_COMMENTS
			  ,(Select WIN_SERVICENAME from CSM_WINDOWS_SERVICES win where win.CONFIG_ID = [CSM_CONFIGURATION].CONFIG_ID) WIN_SERVICENAME
			  ,(Select WIN_SERVICE_ID from CSM_WINDOWS_SERVICES win where win.CONFIG_ID = [CSM_CONFIGURATION].CONFIG_ID) WIN_SERVICE_ID
			  ,usr.USER_FIRST_NAME USERFIRSTNAME
			  ,usr.USER_LAST_NAME USERLASTNAME
		  from [CSM_CONFIGURATION] 
		  inner join [CSM_ENVIRONEMENT] 
		  on [CSM_CONFIGURATION].[ENV_ID] = [CSM_ENVIRONEMENT].[ENV_ID]
		  left join CSM_SCHEDULE on CSM_SCHEDULE.ENV_ID = [CSM_ENVIRONEMENT].[ENV_ID]
		  and  CSM_SCHEDULE.ENV_ID = [CSM_CONFIGURATION].[ENV_ID]
		  and CSM_SCHEDULE.CONGIG_ID =  [CSM_CONFIGURATION].CONFIG_ID
		  and CSM_SCHEDULE.SCH_ENDBY >= GETDATE()
		  join dbo.CSM_USER usr on usr.USER_ID = [CONFIG_CREATED_BY]
		  where [CONFIG_IS_ACTIVE] = 'True' and 	
			[CSM_CONFIGURATION].[CONFIG_ISPRIMARY] = 'True' 
			and [CSM_CONFIGURATION].[ENV_ID] = @ENV_ID	
		End
		else
		Begin
			select
			   [CONFIG_ID]
			  ,[CSM_CONFIGURATION].[ENV_ID]
			  ,[CSM_ENVIRONEMENT].ENV_NAME
			  ,[CONFIG_SERVICE_TYPE]
			  ,[CONFIG_PORT_NUMBER]
			  ,[CONFIG_URL_ADDRESS]
			  ,[CONFIG_DESCRIPTION]
			  ,[CONFIG_IS_VALIDATED]
			  ,[CONFIG_IS_ACTIVE]
			  ,[CONFIG_IS_MONITORED]
			  ,[CONFIG_IS_LOCKED]
			  ,[CONFIG_CREATED_BY]
			  ,[CONFIG_CREATED_DATE]
			  ,[CONFIG_UPDATED_BY]
			  ,[CONFIG_UPDATED_DATE]
			  ,[CONFIG_COMMENTS]
			  ,[CONFIG_HOST_IP]
			  ,[CONFIG_MAIL_FREQ]
			  ,[CONFIG_LOCATION]
			  ,[CONFIG_ISCONSOLIDATED]
			  ,[CONFIG_ISNOTIFY]
			  ,[CONFIG_ISPRIMARY]
			  ,[CONFIG_REF_ID]
			  ,[CSM_SCHEDULE].SCH_ID
			  ,[CSM_SCHEDULE].SCH_COMMENTS
			  ,(Select WIN_SERVICENAME from CSM_WINDOWS_SERVICES win where win.CONFIG_ID = [CSM_CONFIGURATION].CONFIG_ID) WIN_SERVICENAME
			  ,(Select WIN_SERVICE_ID from CSM_WINDOWS_SERVICES win where win.CONFIG_ID = [CSM_CONFIGURATION].CONFIG_ID) WIN_SERVICE_ID
			  ,usr.USER_FIRST_NAME USERFIRSTNAME
			  ,usr.USER_LAST_NAME USERLASTNAME
			  from [CSM_CONFIGURATION] 
		  inner join [CSM_ENVIRONEMENT] on
			[CSM_CONFIGURATION].[ENV_ID] = [CSM_ENVIRONEMENT].[ENV_ID]
		  left outer join CSM_SCHEDULE on CSM_SCHEDULE.ENV_ID = [CSM_ENVIRONEMENT].[ENV_ID]
		  and  CSM_SCHEDULE.ENV_ID = [CSM_CONFIGURATION].[ENV_ID]
		  and CSM_SCHEDULE.CONGIG_ID =  [CSM_CONFIGURATION].CONFIG_ID
		  and CSM_SCHEDULE.SCH_ENDBY >= GETDATE()
		  join dbo.CSM_USER usr on usr.USER_ID = [CONFIG_CREATED_BY]
		  where [CONFIG_IS_ACTIVE] = 'True' and
			[CSM_CONFIGURATION].[CONFIG_ISPRIMARY] = 'True'


		End
	End
End


SET ANSI_NULLS ON


GO
