/****** Object:  StoredProcedure [dbo].[CWT_GetGroupOpenScheduledServceDetails]    Script Date: 10/04/2015 14:02:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE procedure [dbo].[CWT_GetGroupOpenScheduledServceDetails]
(
	 @CURRENTDATETIME datetime
	,@SCHEDULE_STATUS char(1)
	,@Category varchar(10)
	,@GROUP_SCH_ID int
	,@ENV_ID int
)
As
Begin
	if @Category = 'env'
	Begin
	SELECT  distinct cgs.[GROUP_SCH_ID]
		  ,cgs.[GROUP_ID]
		  ,cgsd.ENV_ID
		  ,env.ENV_NAME

	  FROM [CSM_GROUP_SCHEDULE] cgs
	  join [CSM_GROUP_SCHEDULE_DETAIL] cgsd on cgsd.[GROUP_SCH_ID] = cgs.[GROUP_SCH_ID]
	  --join [CSM_CONFIGURATION] con on con.CONFIG_ID = cgsd.CONFIG_ID
	  join [CSM_ENVIRONEMENT] env on env.ENV_ID = cgsd.ENV_ID
	  --join [CSM_WINDOWS_SERVICES] win on win.CONFIG_ID = con.CONFIG_ID
	  where cgsd.GROUP_SCH_ID = @GROUP_SCH_ID
			--con.CONFIG_IS_ACTIVE = 'true'
			--and [GROUP_SCH_TIME] <= CONVERT(VARCHAR(19), @CURRENTDATETIME, 120)
			and LTRIM(RTRIM(cgs.[GROUP_SCH_STATUS])) = @SCHEDULE_STATUS
			and LTRIM(RTRIM(cgsd.GROUP_SCH_STATUS))  = @SCHEDULE_STATUS
			and cgs.GROUP_SCH_ISACTIVE = 'true'
			
	End		
	else if @Category = 'cfg'
	Begin
	SELECT  cgs.[GROUP_SCH_ID]
		  ,cgs.[GROUP_ID]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_TIME], 120) [GROUP_SCH_TIME]
		  ,cgs.[GROUP_SCH_ACTION]
		  ,cgs.[GROUP_SCH_STATUS]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_COMPLETED_TIME], 120) [GROUP_SCH_COMPLETED_TIME]
		  ,cgs.[GROUP_SCH_COMMENTS]
		  ,cgs.[GROUP_SCH_CREATED_BY]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_CREATED_DATETIME], 120) [GROUP_SCH_CREATED_DATETIME]
		  ,cgs.[GROUP_SCH_UPDATED_BY]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_UPDATED_DATETIME], 120) [GROUP_SCH_UPDATED_DATETIME]
		  ,cgs.GROUP_SCH_REQUESTSOURCE
		  ,cgsd.GROUP_SERVICE_SCH_ID
		  ,cgsd.CONFIG_ID
		  ,cgsd.GROUP_SCH_ISACTIVE
		  ,cgsd.GROUP_SCH_STATUS
		  ,con.CONFIG_SERVICE_TYPE
		  ,con.CONFIG_HOST_IP
		  ,con.CONFIG_PORT_NUMBER
		  ,con.ENV_ID
		  ,env.ENV_NAME
		  ,win.WIN_SERVICE_ID
		  ,win.WIN_SERVICENAME
		  ,(cu.USER_FIRST_NAME + ' ' + cu.USER_LAST_NAME) USER_FIRST_NAME
	  FROM [CSM_GROUP_SCHEDULE] cgs
	  join [CSM_GROUP_SCHEDULE_DETAIL] cgsd on cgsd.[GROUP_SCH_ID] = cgs.[GROUP_SCH_ID]
	  join [CSM_CONFIGURATION] con on con.CONFIG_ID = cgsd.CONFIG_ID
	  join [CSM_ENVIRONEMENT] env on env.ENV_ID = con.ENV_ID
	  join [CSM_WINDOWS_SERVICES] win on win.CONFIG_ID = con.CONFIG_ID
	  join [CSM_USER] cu on cu.USER_ID = cgs.[GROUP_SCH_CREATED_BY]
	  where cgsd.GROUP_SCH_ID = @GROUP_SCH_ID
			and cgsd.ENV_ID = @ENV_ID 
			and LTRIM(RTRIM(cgs.[GROUP_SCH_STATUS])) = @SCHEDULE_STATUS
			and LTRIM(RTRIM(cgsd.GROUP_SCH_STATUS))  = @SCHEDULE_STATUS
			and cgs.GROUP_SCH_ISACTIVE = 'true'
			and cgsd.GROUP_SCH_ISACTIVE = 'true'
			order by cgsd.GROUP_SERVICE_SCH_ID
	  
			--and [GROUP_SCH_TIME] <= CONVERT(VARCHAR(19), @CURRENTDATETIME, 120)

	End		
	else if @Category = 'sch'
	Begin
	SELECT  cgs.[GROUP_SCH_ID]
		  ,cgs.[GROUP_ID]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_TIME], 120) [GROUP_SCH_TIME]
		  ,cgs.[GROUP_SCH_ACTION]
		  ,cgs.[GROUP_SCH_STATUS]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_COMPLETED_TIME], 120) [GROUP_SCH_COMPLETED_TIME]
		  ,cgs.[GROUP_SCH_COMMENTS]
		  ,cgs.[GROUP_SCH_CREATED_BY]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_CREATED_DATETIME], 120) [GROUP_SCH_CREATED_DATETIME]
		  ,cgs.[GROUP_SCH_UPDATED_BY]
		  ,CONVERT(VARCHAR(19), cgs.[GROUP_SCH_UPDATED_DATETIME], 120) [GROUP_SCH_UPDATED_DATETIME]
		  ,cgs.GROUP_SCH_REQUESTSOURCE
		  ,grp.GROUP_NAME
		  ,(cu.USER_FIRST_NAME + ' ' + cu.USER_LAST_NAME) USER_FIRST_NAME
	  FROM [CSM_GROUP_SCHEDULE] cgs
	  join [CSM_GROUP] grp on grp.GROUP_ID = cgs.GROUP_ID
	  join [CSM_USER] cu on cu.USER_ID = cgs.[GROUP_SCH_CREATED_BY]
	  where 
			[GROUP_SCH_TIME] <= CONVERT(VARCHAR(19), @CURRENTDATETIME, 120)
			and LTRIM(RTRIM([GROUP_SCH_STATUS])) = @SCHEDULE_STATUS
			and cgs.GROUP_SCH_ISACTIVE = 'true'

	End		
End
SET ANSI_NULLS ON


GO
