/****** Object:  StoredProcedure [dbo].[CWT_GetWindowsServiceDetails]    Script Date: 06/26/2015 14:20:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[CWT_GetWindowsServiceDetails]
(
	@ENV_ID int
)
as
Begin
	if(@ENV_ID>0 or @ENV_ID is not null)
	Begin
	if @ENV_ID > 0
	Begin
		select 
			[CSM_ENVIRONEMENT].[ENV_ID]
			,[CSM_ENVIRONEMENT].[ENV_NAME]
			,[CSM_CONFIGURATION].[CONFIG_ID]
			,[CSM_CONFIGURATION].[CONFIG_HOST_IP]
			,[CSM_CONFIGURATION].[CONFIG_SERVICE_TYPE]
			,[CSM_CONFIGURATION].[CONFIG_PORT_NUMBER]
			,[CSM_CONFIGURATION].[CONFIG_LOCATION]
			,[CSM_CONFIGURATION].[CONFIG_ISPRIMARY]
			,[CSM_WINDOWS_SERVICES].[WIN_SERVICE_ID]
			,[CSM_WINDOWS_SERVICES].[WIN_SERVICENAME]
			,[CSM_WINDOWS_SERVICES].[WIN_COMMENTS]
			,[CSM_WINDOWS_SERVICES].[WIN_CREATED_BY]
			,[CSM_WINDOWS_SERVICES].[WIN_CREATED_DATE]
			,[CSM_WINDOWS_SERVICES].[WIN_UPDATED_BY]
			,[CSM_WINDOWS_SERVICES].[WIN_UPDATED_DATE]

		from [CSM_CONFIGURATION]
			left join [CSM_WINDOWS_SERVICES] on [CSM_WINDOWS_SERVICES].[CONFIG_ID] = [CSM_CONFIGURATION].[CONFIG_ID] 
				and [CSM_WINDOWS_SERVICES].[ENV_ID] = [CSM_CONFIGURATION].[ENV_ID]
			inner join [CSM_ENVIRONEMENT] on [CSM_CONFIGURATION].[ENV_ID] = [CSM_ENVIRONEMENT].[ENV_ID]
		where [CSM_CONFIGURATION].[CONFIG_IS_ACTIVE] = 'True'
				and [CSM_CONFIGURATION].[CONFIG_ISPRIMARY] = 'True'
				and [CSM_CONFIGURATION].[ENV_ID] = @ENV_ID
		End
		else if(@ENV_ID<=0)
		Begin
		select 
			[CSM_ENVIRONEMENT].[ENV_ID]
			,[CSM_ENVIRONEMENT].[ENV_NAME]
			,[CSM_CONFIGURATION].[CONFIG_ID]
			,[CSM_CONFIGURATION].[CONFIG_HOST_IP]
			,[CSM_CONFIGURATION].[CONFIG_SERVICE_TYPE]
			,[CSM_CONFIGURATION].[CONFIG_PORT_NUMBER]
			,[CSM_CONFIGURATION].[CONFIG_LOCATION]
			,[CSM_CONFIGURATION].[CONFIG_ISPRIMARY]
			,[CSM_WINDOWS_SERVICES].[WIN_SERVICE_ID]
			,[CSM_WINDOWS_SERVICES].[WIN_SERVICENAME]
			,[CSM_WINDOWS_SERVICES].[WIN_COMMENTS]
			,[CSM_WINDOWS_SERVICES].[WIN_CREATED_BY]
			,[CSM_WINDOWS_SERVICES].[WIN_CREATED_DATE]
			,[CSM_WINDOWS_SERVICES].[WIN_UPDATED_BY]
			,[CSM_WINDOWS_SERVICES].[WIN_UPDATED_DATE]

		from [CSM_CONFIGURATION]
			left join [CSM_WINDOWS_SERVICES] on [CSM_WINDOWS_SERVICES].[CONFIG_ID] = [CSM_CONFIGURATION].[CONFIG_ID] 
				and [CSM_WINDOWS_SERVICES].[ENV_ID] = [CSM_CONFIGURATION].[ENV_ID]
			inner join [CSM_ENVIRONEMENT] on [CSM_CONFIGURATION].[ENV_ID] = [CSM_ENVIRONEMENT].[ENV_ID]
		where [CSM_CONFIGURATION].[CONFIG_IS_ACTIVE] = 'True'
				and [CSM_CONFIGURATION].[CONFIG_ISPRIMARY] = 'True'
				and [CSM_CONFIGURATION].[ENV_ID] = @ENV_ID
		End
		
	End
End
	
/****** Object:  StoredProcedure [dbo].[CWT_GetAllScheduledServices]    Script Date: 2/9/2015 6:00:04 PM ******/
SET ANSI_NULLS ON


--exec CWT_GetWindowsServiceDetails 1
GO


