SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE procedure [dbo].[CWT_GetUrlPerformanceLast24Hours](@ENVID int)
As
Begin
	if @ENVID > 0
	Begin
		SELECT CONVERT(DECIMAL(5,2), sum(pm.PMON_RESPONSETIME)/1000.0) TOTALRT, CONVERT(DECIMAL(5,2), avg(pm.PMON_RESPONSETIME)/1000.0) AVGRT, DATEPART(hh, pm.PMON_CREATEDDATE) HOURRT,DATEPART(DAY, pm.PMON_CREATEDDATE) DATERT
		  from dbo.[CSM_PORTALMONITOR] pm
		  where pm.PMON_RESPONSETIME > 0
		  and pm.PMON_CREATEDDATE >= dateadd(hh, -23,GETDATE())
		  and  pm.PMON_CREATEDDATE <= GETDATE()
		  and pm.ENV_ID = @ENVID
		  GROUP BY DATEPART(hh, pm.PMON_CREATEDDATE),DATEPART(DAY, pm.PMON_CREATEDDATE)
		  		  order by DATERT, HOURRT

	End
	else
	Begin
		SELECT CONVERT(DECIMAL(5,2), sum(pm.PMON_RESPONSETIME)/1000.0) TOTALRT, CONVERT(DECIMAL(5,2), avg(pm.PMON_RESPONSETIME)/1000.0) AVGRT, DATEPART(hh, pm.PMON_CREATEDDATE) HOURRT,DATEPART(DAY, pm.PMON_CREATEDDATE) DATERT
		  from dbo.[CSM_PORTALMONITOR] pm
		  where pm.PMON_RESPONSETIME > 0
		  and pm.PMON_CREATEDDATE >= dateadd(hh, -23,GETDATE())
		  and  pm.PMON_CREATEDDATE <= GETDATE()
		  GROUP BY DATEPART(hh, pm.PMON_CREATEDDATE),DATEPART(DAY, pm.PMON_CREATEDDATE)
		  order by DATERT, HOURRT

	End
End
GO


